 
version: '3.8'

services:
  app1:
    build:
      context: ./DocTracar
      dockerfile: Dockerfile
    ports:
      - "8081:8082"
    networks:
      - shared-network

  app2:
    build:
      context: ./DocCpp
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge
